#4 여러 개의 입력(feature)의 Linear Regression

## tf.matmul 함수를 통하여 Matrix multiplication

Predicting exam score :
regression using three inputs(x1,x2,x3)
- x1 x2 x3 Y
- 73 80 75 152
- 93 88 913 185
- 89 91 90 180
- 96 98 100 196
- 19 66 70 142
- Test score for General Psychology

- hypothesis : H(x1,x2,x3)=w1x1+w2x2+w3x3+b
- cost(W,b)=1/m sum(H(x1(i),x2(i),x3(i))-y(i))^2

- Matrix multiplication - Dot product

- w1x1+w2x2+w3x3_...+wnxn
- (x1,x2,x3) dot (w1,w2,w3)T = (x1w1+x2w2+x3w3)
- H(X)=xW



# 4.2 Multiple-variable linear regression
- 여러 개의 입력이 있는 경우의 linear regression

## 1. 실습 목적
- 여러개의 입력이 있는 경우의 linear regression의 기본 구조를 익힌다.

## 2. 간단한 API 및 간단한 설명
- 여러개의 입력이 있는 경우의 linear regression처리
- 여러 입력을 각각의 1행 5열 배열로 처리

    - x1_data=[73.,93.,89.,96.,73.]
    - x2_data=[...................]
    - x3_data=[...................]
    - y_data=[152.,185.,180.,196.,142.]

- hypothesis = x1*w1+x2*w2+x3*w3+b : 여러 입력에 대한 hypothesis적용

- cost_val,hy_val,_=sess.run([cost,hypothesis,train],feed_dict={x1:x1_data,x2:x2_data,x3:x3_data})
- feed_dict를 통하여 여러입력을 대입





In [9]:
# Lab 4-1 Multi-variable linear regression

import tensorflow as tf

tf.set_random_seed(00)
x1_data=[73.,93.,89.,96.,73.]
x2_data=[80.,89.,91.,98.,66.]
x3_data=[75.,93.,90.,100.,70]

y_data=[152.,185.,180.,196.,142]

 # placeholders for a tensor that will be always fed
x1=tf.placeholder(tf.float32)
x2=tf.placeholder(tf.float32)
x3=tf.placeholder(tf.float32)

Y=tf.placeholder(tf.float32)

W1=tf.Variable(tf.random_normal([1]),name='weight1')
W2=tf.Variable(tf.random_normal([1]),name='weight2')
W3=tf.Variable(tf.random_normal([1]),name='weight3')
b=tf.Variable(tf.random_normal([1]),name='bias')

# Set hypothesis
hypothesis=x1*W1+x2*W2+x3*W3+b
print(hypothesis)

# Cost function
cost=tf.reduce_mean(tf.square(hypothesis-Y))

# Minimize. Need a very small learning rate for this data set
optimizer=tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train=optimizer.minimize(cost)

# Launch the graph in a session
sess=tf.Session()

# initializes gloval variables
sess.run(tf.global_variables_initializer())

for step in range(2000):
    cost_val,hy_val,_=sess.run([cost,hypothesis,train],feed_dict={x1:x1_data,x2:x2_data,x3:x3_data,Y:y_data})
    print(step,"Cost",cost_val,"\nPrediction:\n",hy_val)


 Cost 8.044647 
Prediction:
 [155.33804 182.65855 181.63338 197.23335 137.5944 ]
1767 Cost 8.040773 
Prediction:
 [155.33704 182.65913 181.6331  197.23312 137.59537]
1768 Cost 8.036868 
Prediction:
 [155.33603 182.65973 181.63283 197.23291 137.59634]
1769 Cost 8.032942 
Prediction:
 [155.335   182.66032 181.63255 197.2327  137.59732]
1770 Cost 8.02904 
Prediction:
 [155.33401 182.66092 181.63226 197.23247 137.5983 ]
1771 Cost 8.025148 
Prediction:
 [155.33302 182.66151 181.63197 197.23225 137.59927]
1772 Cost 8.021225 
Prediction:
 [155.332   182.66211 181.6317  197.23204 137.60025]
1773 Cost 8.017309 
Prediction:
 [155.33101 182.66272 181.63142 197.23184 137.60124]
1774 Cost 8.013423 
Prediction:
 [155.33    182.6633  181.63115 197.23163 137.60222]
1775 Cost 8.009514 
Prediction:
 [155.329   182.6639  181.63086 197.23141 137.6032 ]
1776 Cost 8.005635 
Prediction:
 [155.32799 182.66449 181.63058 197.23119 137.60416]
1777 Cost 8.001762 
Prediction:
 [155.327   182.66507 181.6303  197.23