# 4.2 Multi Variable linear regression with tf.matmul

## 1. 실습 목적
- matmul 함수 사용법을 익힌다.
- 텐서의 변경 사항을 익힌다.

## 2. 사용한 AIP및 간단한 설명

- matmul 함수 사용.
- 5x3 배열 생성
    - x_data=[[73.,80.,75.],[93.,88.,93.], [89.,91.,90.], [96.,98.,100.], [73.,66.,70.]]
    - y_data=[[152.],
            [180.],
            [196.],
            142]]
- 5X1 배열 생성

- hypothesis=tf.matmul(X,W)+b
    - X:5x3, Y:5x1 matrix multiplier 수행 수 b와 더함.
    - matmul

In [7]:
# Lab 4-2 Multi-variable Linear Regression

import tensorflow as tf
tf.set_random_seed(000)

x_data=[[73.,80.,75.],[93.,88.,93.],[89.,91.,90.],[96.,98.,100.],[73.,66.,70.]]
y_data=[[152.],[185.],[180.],[196.],[142.]]

# placeholders for a tensor that will be always fed
X=tf.placeholder(tf.float32,shape=[None,3])
Y=tf.placeholder(tf.float32,shape=[None,1])

W=tf.Variable(tf.random_normal([3,1]),name='weight') 
b=tf.Variable(tf.random_normal([1]),name='bias')

# Hypothesis
hypothesis=tf.matmul(X,W)+b

# Simplified cost/loss function
cost=tf.reduce_mean(tf.square(hypothesis-Y))

# Minimize
optimizer=tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train=optimizer.minimize(cost)

# Launch the graph in a session
sess=tf.Session()

# Initialize global variables 
sess.run(tf.global_variables_initializer())

for step in range(2000):
    cost_val,hy_val,_=sess.run([cost,hypothesis,train],feed_dict={X:x_data,Y:y_data})
    if step%10==0:
        print(step,"cost:",cost_val,"\nPrediction\n",hy_val)
    

0 cost: 13785.542 
Prediction
 [[49.98619 ]
 [57.825462]
 [58.62226 ]
 [60.40869 ]
 [45.927246]]
10 cost: 2.991475 
Prediction
 [[153.83475]
 [182.65324]
 [181.6122 ]
 [194.34273]
 [141.14088]]
20 cost: 2.8563733 
Prediction
 [[154.14388]
 [183.03433]
 [181.98268]
 [194.74727]
 [141.43303]]
30 cost: 2.847493 
Prediction
 [[154.13976]
 [183.03888]
 [181.98218]
 [194.7478 ]
 [141.43796]]
40 cost: 2.8386445 
Prediction
 [[154.13472]
 [183.0423 ]
 [181.98058]
 [194.74716]
 [141.44205]]
50 cost: 2.8298717 
Prediction
 [[154.12968]
 [183.04572]
 [181.97899]
 [194.74646]
 [141.44609]]
60 cost: 2.8211017 
Prediction
 [[154.12465]
 [183.0491 ]
 [181.97737]
 [194.7458 ]
 [141.45012]]
70 cost: 2.8124156 
Prediction
 [[154.11964]
 [183.05247]
 [181.97577]
 [194.74512]
 [141.45416]]
80 cost: 2.803768 
Prediction
 [[154.11465]
 [183.05585]
 [181.97418]
 [194.74446]
 [141.45818]]
90 cost: 2.7951407 
Prediction
 [[154.10965]
 [183.0592 ]
 [181.97258]
 [194.74379]
 [141.46217]]
100 cost: 2.786571 
Pred