# 6.1 Softmax classifier </br>

(1) 실습 목적 

- 간단한 softmax 구현 함수를 익힌다.</br>

(2) 사용한 API 및 간단한 설명

- hypothesis=tf.nn.softmax(tf.matmul(X,W)+b)
    - hypothesis 에서 tf.matmul(X,W)+b에 tf.nn.softmax 함수 적용
- cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis),axis=1))
    - Cross entropy를 코스트 함수로 사용한다.
- optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)
    - learning_rate = 0.l로 학습을 진행함.</br>
    
## Hypothesis 행렬 식

## $\begin{bmatrix} 0 \ \  0 \ \  1 \\ 0 \ \ 0 \ \  1 \\ 0 \ \  0 \ \ 1 \\ 0 \ \ 1 \ \ 0 \\ 0 \ \  1 \ \  0 \\ 0 \ \ 1 \ \  1 \\ 1 \ \  0 \ \ 0 \\ 1 \ \ 0 \ \ 0 \\ \end{bmatrix}_{Y(8*3)}$ = softmax($\begin{bmatrix} 1 \ \ 2 \ \ 1 \ \ 1 \\ 2 \ \ 1 \ \ 3 \ \ 2 \\ 3 \ \ 1 \ \ 3 \ \ 4 \\ 4 \ \ 1 \ \ 5 \ \ 5 \\ 1 \ \ 7 \ \ 5 \ \ 5 \\ 1 \ \ 2 \ \ 5 \ \ 6 \\ 1 \ \ 6 \ \ 6 \ \ 6 \\ 1 \ \ 7 \ \ 7 \ \ 7 \\ \end{bmatrix}_{X(8*4)}$ x $\begin{bmatrix} 0 \ \  0 \ \  1 \\ 0 \ \ 0 \ \  1 \\ 0 \ \  0 \ \ 1 \\ 0 \ \ 1 \ \ 0 \\ \end{bmatrix}_{Weight(4*3)}$ $+$ $\begin{bmatrix} 1 \ \ 2 \ \ 3 \ \end{bmatrix}_{Bias(1*3)}$)


In [8]:
# Lab 6-1 Softmax Classifier

import tensorflow as tf
tf.set_random_seed(000)

#1. raw data
x_data=[[1,2,1,1],[2,1,3,2],[2,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]] #8X4
y_data=[[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,1],[1,0,0],[1,0,0]] #8X3

# 2. raw data를 넣을 place holder 생성
X=tf.placeholder("float",[None,4])
Y=tf.placeholder("float",[None,3])
nb_classes=3

# 3. Weight , Bias를 넣을 Variable 생성.
W=tf.Variable(tf.random_normal([4,nb_classes]),name='Weight')
b=tf.Variable(tf.random_normal([nb_classes]),name='bias')

# tf.nn.softmax compute softmax activations 
# softmax=exp(logits)/reduce_sum(exp(logits),dim)

hypothesis=tf.nn.softmax(tf.matmul(X,W)+b)

# Cross entropy cost function
cost=tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis),axis=1))
optimizer=tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Launch the graph
with tf.Session() as sess:
    
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        # 1. 훈령
        sess.run(optimizer,feed_dict={X:x_data,Y:y_data})
        if step%200==0:
            print(step,sess.run(cost,feed_dict={X:x_data,Y:y_data}))
    
    print('-------------------------')

    # Testing & One-hot encoding
    a=sess.run(hypothesis,feed_dict={X:[[1,11,7,9]]})
    print(a,sess.run(tf.argmax(a,1)))


    print('-------------------------')

    b=sess.run(hypothesis,feed_dict={X:[[1,3,4,3]]})
    print(b,sess.run(tf.argmax(b,1)))

    print('-------------------------')

    c=sess.run(hypothesis,feed_dict={X:[[1,1,0,1]]})
    print(c,sess.run(tf.argmax(c,1)))
    
    print('-------------------------')

    all=sess.run(hypothesis,feed_dict={X:[[1,11,7,9],[1,3,4,3],[1,1,0,1]]})
    print(all,sess.run(tf.argmax(all,1)))




0 2.0874891
200 0.7741214
400 0.6366739
600 0.5488541
800 0.4769693
1000 0.40989822
1200 0.37069127
1400 0.35279408
1600 0.3379337
1800 0.32537127
2000 0.31459957
-------------------------
[[4.4100652e-03 9.9558002e-01 9.8883074e-06]] [1]
-------------------------
[[0.61517763 0.08948574 0.29533666]] [0]
-------------------------
[[8.6745352e-08 3.7492781e-03 9.9625069e-01]] [2]
-------------------------
[[4.4100652e-03 9.9558002e-01 9.8883174e-06]
 [6.1517763e-01 8.9485720e-02 2.9533663e-01]
 [8.6745352e-08 3.7492781e-03 9.9625069e-01]] [1 0 2]
