In [14]:
# Lab 6 Softmax Classifier
import torch
from torch.autograd import Variable

torch.manual_seed(000)

x_data=[[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],
[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]]
y_data=[[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

X=Variable(torch.Tensor(x_data))
Y=Variable(torch.Tensor(y_data))
nb_classes=3

# tf.nn.softmax computes softmax activations
# softmax=exp(logits)/reduce_sum(exp(logits),dim)

softmax=torch.nn.Softmax()
linear=torch.nn.Linear(4,nb_classes,bias=True) # tf.model.add(tf.keras.layers.Dense(input_dim=4,units=nb_classes,use_bias=True))
model=torch.nn.Sequential(linear,softmax)

optimizer=torch.optim.SGD(model.parameters(),lr=0.01)

for step in range(2001):
    optimizer.zero_grad() #w,b 초기화
    hypothesis=model(X)
    # cross entropy cost
    cost=-Y*torch.log(hypothesis)
    cost=torch.sum(cost,1).mean()
    optimizer.step()

    if step%200==0:
        print(step,cost.data.numpy())
    
# Testing & One-hot encoding
print('----------------')
a=model(Variable(torch.Tensor([[1,11,7,9]])))
print(a.data.numpy(),torch.max(a,1)[1].data.numpy())

print('----------------')
b=model(Variable(torch.Tensor([[1,3,4,2]])))
print(b.data.numpy(),torch.max(b,1)[1].data.numpy())

print('----------------')
c=model(Variable(torch.Tensor([[1,1,0,1]])))
print(c.data.numpy(),torch.max(c,1)[1].data.numpy())

print('----------------')
all=model(Variable(torch.Tensor([[1,11,7,9],[1,3,4,2],[1,1,0,1]])))
print(all.data.numpy(),torch.max(all,1)[1].data.numpy())
print(all.data.numpy(),torch.max(all,1))

0 2.2566257
200 2.2566257
400 2.2566257
600 2.2566257
800 2.2566257
1000 2.2566257
1200 2.2566257
1400 2.2566257
1600 2.2566257
1800 2.2566257
2000 2.2566257
----------------
[[2.8047728e-04 9.9416453e-01 5.5549787e-03]] [1]
----------------
[[0.05047361 0.7439792  0.20554726]] [1]
----------------
[[0.23582566 0.42456424 0.3396101 ]] [1]
----------------
[[2.8047728e-04 9.9416453e-01 5.5549787e-03]
 [5.0473597e-02 7.4397922e-01 2.0554723e-01]
 [2.3582566e-01 4.2456424e-01 3.3961010e-01]] [1 1 1]
[[2.8047728e-04 9.9416453e-01 5.5549787e-03]
 [5.0473597e-02 7.4397922e-01 2.0554723e-01]
 [2.3582566e-01 4.2456424e-01 3.3961010e-01]] torch.return_types.max(
values=tensor([0.9942, 0.7440, 0.4246], grad_fn=<MaxBackward0>),
indices=tensor([1, 1, 1]))
